version: '3.3'
services:
  nginx:
    container_name: webserver_nginx
    build: 
      context: .
      dockerfile: ./nginx/Dockerfile
    command: nginx -g "daemon off;"
    ports:
      - "80:80"
    links:
      - php
    # networks:
    #   - web
    
    
  php:
    container_name: web_php
    build: 
      context: .
      dockerfile: ./php/Dockerfile
    working_dir: /var/www/html
    # networks:
    #   - web
    
# networks:
#   web:
#     driver: bridge
    
      
    